### ISSUE TITLE
[ENH] forecasting: ensure compositors (pipeline, tuning) work for multivariate forecasters

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1364]
From the Aug 27 developer meeting.

We need to ensure that the following compositors work for multivariate forecasters, in descending order of priority
- [x] pipeline compositors, `TransformedTargetForecaster`, `ForecastingPipeline` #1376 
- [x] tuning compositors, `ForecastingGridSearchCV`, `ForecastingRandomizedSearchCV` #1376 
- [ ] reducers, all in the `_reduce` module, see #1038
- [ ] multiplexing, `MultiplexForecaster`
- [ ] ensembles, `EnsembleForecaster`, `AutoEnsembleForecaster`
- [ ] stacking, `StackingForecaster`

Some of these might be slightly challenging, but still good first issues.
As usual, we use this issue to track who is working on what, please indicate your pick before starting work on it.

**Comment by aiwalter** [comment]
I added this also to the wish list, but lets keep track here then. I will pick the `TransformedTargetForecaster` as a start :). After my test refactor contained in #1347 is merged.

**Comment by aiwalter** [comment]
can we add `NaiveForecaster` to this list? It could internally just apply a `ColumnEnsembleForecaster`

**Comment by aiwalter** [comment]
What about `ForecastingPipeline`? Do we need to adjust it? Not sure if there is a use-case where `y` and `X` are both `pd.DataFrame`?

**Comment by fkiraly** [comment]
Yes, I think that´s not an uncommon use case.

Btw, it looks like `TransformedTargetForecaster` works for multivairate out of the box?

**Comment by mloning** [comment]
> Btw, it looks like `TransformedTargetForecaster` works for multivairate out of the box?

No, still only works for univariate input data.

**Comment by aiwalter** [comment]
I have a PR open for `TransformedTargetForecaster` and `BaseGridSearch`, see #1376 . Need to wait merging #1301
