### ISSUE TITLE
re-factoring existing forecasters to new interface

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#955]
We need to slowly re-factor all forecasters to be compliant with the new interface (see PR #912). i.e., no overrides of `fit` etc and descendant classes only implementing core logic, while the `BaseForecaster` implements check etc logic.

Currently this is running due to various downwards compatibility workarounds, which should be removed once all forecasters are ready (in "no-override" state)

The forecasters that still need a downstream refactor are:
 * [x] `NaiveForecasters` #953
 * [x]  `EnsembleForecaster` #977
 * [x]  `MultiplexForecaster` #977
 * [x]  `TransformedTargetForecaster` #977
 * [x]  `_Reducer` and related code #1031
 * [x]  `StackingForecaster` #977
 * [x]  `ForecastingGridSearchCV`, `RandomizedGridSearchCV`, and `BaseGridSearch` #1034
 * [x]  `OnlineEnsembleForecaster` and descendants #1015
 * [x]  `_PmdArimaAdapter` and descendants `ARIMA`, `AutoARIMA` #1016 - adapter only
 * [x]  `BATS`, `TBATS`, and `_Tbatsadapter` #1017 adapter only
 * [x]  `_StatsModelAdapter` and descendants `AutoETS`, `ExponentialSmoothing`, `ThetaForecaster`  #1029
 * [x]  `HCrystalBallForecaster` #1004
 * [x]  `Prophet` and `_ProphetAdapter` #1005
 * [x]  `PolynomialTrendForecaster` #1003

For a how-to, useful resources are the forecaster extension template in `extension_templates` and PR #953 as an example for `NaiveForecaster`.

Based on discussions, we need to do the following two things in a capstone refactor that removes the last traces of the workarounds and goes over the above for consistency:
- [x] remove the `_SktimeForecaster` and mixins for good
- [ ] go through all forecasters and check the tags for correctness

**Comment by thayeylolu** [comment]
Thank you @fkiraly . I shall begin work on this. And make a draft shortly

**Comment by fkiraly** [comment]
For convenience, I'm adding a recipe here:

* go through all the public methods, `fit`, `predict`, etc, and change them to the new private version `_fit`, `_predict`, etc
* remove input checks (e.g., `check_X`) and output operations (e.g., set cutoff) from the private version; make sure these are already all present in the `BaseForecaster`.
* if there's an input or output check/operation that looks like it should be in `BaseForecaster` but isn't, add a note to your PR and make it very explicit; consider adding it to `BaseForecaster` but make sure @mloning and @fkiraly are aware of such a change.
* make sure all the tests pass. Don't change any of the tests.
* if there's an inheritance tree (not just a single class) downstream from `BaseForecaster`, make sure you do the above for all nodes in the inheritance tree

**Comment by fkiraly** [comment]
FYI, @thayeylolu - not sure whether you´ve seen the "recipe" for the refactor.

**Comment by Lovkush-A** [comment]
@fkiraly @mloning This is easily something i could help with next week (and in the weeks after that). Let me know if that is sensible

**Comment by fkiraly** [comment]
I think @thayeylolu might be done by then already 😃
We could do the same for time series classification though?

**Comment by thayeylolu** [comment]
> FYI, @thayeylolu - not sure whether you´ve seen the "recipe" for the refactor.

What recipe is that? . :)

**Comment by fkiraly** [comment]
>What recipe is that? . :)

@thayeylolu, I meant my second post above, a step-by-step guide for the refactoring.
In case that caused misunderstanding, "recipe" is not just used for food, but also for detailed step-by-step instructions of any other kind.

**Comment by thayeylolu** [comment]
Ah! @fkiraly  Okay. I will look at it

**Comment by fkiraly** [comment]
I've updated the recipe, since I didn't talk about the tags and which parent classes to replace.

**Comment by fkiraly** [comment]
Just so we don't forget:

arising from #912, we need to remove the superfluous `_SktimeForecaster` and mixins at the end.

**Comment by fkiraly** [comment]
... almost there ...

**Comment by fkiraly** [comment]
added two capstone tasks - @mloning, @aiwalter, anything you feel is missing to complete this?

**Comment by Lovkush-A** [comment]
@fkiraly. As a third item, I suggest getting rid of `_sktime.py` altogether. The only things in there are `_SktimeForecaster` (to be deleted), the mixins (to be deleted) and `_BaseWindowForecaster` (which I suggest moving into `_base.py`).

I also suggest refactoring `_BaseWindowForecaster` but it is better to do that in #982 as BaseWindowForecaster predominantly deals with defining predicts and updates

**Comment by Lovkush-A** [comment]
@GuzalBulatova Are you still working on refactoring of grid search? I see the PR above has been closed.

**Comment by fkiraly** [comment]
>@fkiraly. As a third item, I suggest getting rid of `_sktime.py` altogether. The only things in there are `_SktimeForecaster` (to be deleted), the mixins (to be deleted) and `_BaseWindowForecaster` (which I suggest moving into _base.py).

I'm not sure about the `BaseWindowForecaster`. I think there are more important items to work on, such as refactoring transformers or TSC.

But if you have a good idea how to refactor, please go ahead, open an issue that describes what you are going to do, and make a proposal in an PR. Make sure you don't delete the other classes, until the grid search refactor is finished.

**Comment by mloning** [comment]
I think this has been a huge effort by everyone involved, I would treat the tag item separately, should we have a meeting on that to agree on a set of tags for forecasting? After that we make sure tags have been correctly assigned and write tests.

**Comment by fkiraly** [comment]
Well, I put the "tags revisited" here since in our discussion it appeared we need to review them after the refactor. Happy to do this as part of a larger tag refactor #981 though.

**Comment by mloning** [comment]
Having merged #1088, I suggest we close this issue and discuss tags as part of #981

**Comment by fkiraly** [comment]
Yes, indeed.
